# Generated by Django 3.0.2 on 2020-02-16 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('pre_target', models.FloatField()),
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True)),
                ('id_card_x', models.CharField(max_length=64, null=True)),
                ('auth_time', models.CharField(max_length=64, null=True)),
                ('phone', models.CharField(max_length=64, null=True)),
                ('credit_score', models.CharField(max_length=64, null=True)),
                ('overdraft', models.CharField(max_length=64, null=True)),
                ('quota', models.CharField(max_length=64, null=True)),
                ('appl_sbm_tm', models.CharField(max_length=64, null=True)),
                ('sex', models.CharField(max_length=64, null=True)),
                ('birthday', models.CharField(max_length=64, null=True)),
                ('hobby', models.CharField(max_length=128, null=True)),
                ('merriage', models.CharField(max_length=64, null=True)),
                ('income', models.CharField(max_length=64, null=True)),
                ('id_card_y', models.CharField(max_length=64, null=True)),
                ('degree', models.CharField(max_length=64, null=True)),
                ('industry', models.CharField(max_length=64, null=True)),
                ('qq_bound', models.CharField(max_length=64, null=True)),
                ('wechat_bound', models.CharField(max_length=64, null=True)),
                ('account_grade', models.CharField(max_length=64, null=True)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('u_pwd', models.CharField(max_length=16)),
                ('u_identity', models.CharField(choices=[('AD', 'admin')], max_length=2)),
            ],
        ),
    ]
