# Generated by Django 3.0.2 on 2020-01-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('u_pwd', models.CharField(max_length=16)),
                ('u_identity', models.CharField(choices=[('AD', 'admin')], max_length=2)),
            ],
        ),
    ]
