# Generated by Django 3.0.2 on 2020-02-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('pre_target', models.FloatField()),
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True)),
                ('id_card_x', models.CharField(max_length=18, null=True)),
                ('auth_time', models.CharField(max_length=32, null=True)),
                ('phone', models.CharField(max_length=32, null=True)),
                ('credit_score', models.CharField(max_length=32, null=True)),
                ('overdraft', models.CharField(max_length=32, null=True)),
                ('quota', models.CharField(max_length=32, null=True)),
                ('appl_sbm_tm', models.CharField(max_length=32, null=True)),
                ('sex', models.CharField(max_length=32, null=True)),
                ('birthday', models.CharField(max_length=32, null=True)),
                ('hobby', models.CharField(max_length=32, null=True)),
                ('merriage', models.CharField(max_length=32, null=True)),
                ('income', models.CharField(max_length=32, null=True)),
                ('id_card_y', models.CharField(max_length=32, null=True)),
                ('degree', models.CharField(max_length=32, null=True)),
                ('industry', models.CharField(max_length=32, null=True)),
                ('qq_bound', models.CharField(choices=[('Y', 'has_bind'), ('N', 'not_blind')], max_length=2, null=True)),
                ('wechat_bound', models.CharField(choices=[('Y', 'has_bind'), ('N', 'not_blind')], max_length=2, null=True)),
                ('account_grade', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
