# Generated by Django 3.0.2 on 2020-02-14 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
    ]
