# Generated by Django 3.0.2 on 2020-02-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appuser_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='id_card_x',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='qq_bound',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='wechat_bound',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
