# Generated by Django 3.0.2 on 2020-02-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200214_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_file',
            field=models.ImageField(null=True, upload_to='csv_upload'),
        ),
    ]
