# Generated by Django 3.0.2 on 2020-02-16 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_u_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='u_file',
        ),
    ]
